services:
  camera:
    build: ./camera
    runtime: nvidia
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "test", "-f", "/dev/shm/frame.npy"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: unless-stopped



  vision_b:
    build: ./vision_b
    runtime: nvidia
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
      - ./vision_b/models:/vision_b/models
    healthcheck:
      test: ["CMD", "test", "-f", "/dev/shm/vision_b_ready"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: unless-stopped




  vision_c:
    build: ./vision_c
    runtime: nvidia
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
      - ./vision_c/models:/vision_c/models
    healthcheck:
      test: ["CMD", "test", "-f", "/dev/shm/vision_c_ready"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: unless-stopped



  vision_d:
    build: ./vision_d
    runtime: nvidia
    ipc: host

    volumes:
      - /dev/shm:/dev/shm
      - ./vision_d/models:/vision_d/models
    healthcheck:
      test: ["CMD", "test", "-f", "/dev/shm/vision_d_ready"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: unless-stopped




  viewer:
    build: ./viewer
    runtime: nvidia
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped
    depends_on:
     camera:
       condition: service_healthy
     vision_b:
       condition: service_healthy
     vision_c:
       condition: service_healthy
     vision_d:
       condition: service_healthy

