FROM ultralytics/ultralytics:latest-jetson-jetpack6

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Denver

# Optional: Install extra Python packages
RUN pip install --no-cache-dir numpy opencv-python


