services:
  camera:
    build: ./camera
    runtime: nvidia
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    volumes:
      - /dev/shm:/dev/shm

  vision_b:
    build: ./vision_b
    runtime: nvidia
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
      - ./vision_b/models:/vision_b/models


  vision_c:
    build: ./vision_c
    runtime: nvidia
    ipc: host
    volumes:
      - /dev/shm:/dev/shm
      - ./vision_c/models:/vision_c/models
   



  vision_d:
    build: ./vision_d
    runtime: nvidia
    ipc: host

    volumes:
      - /dev/shm:/dev/shm
      - ./vision_c/models:/vision_c/models


  viewer:
    build: ./viewer
    runtime: nvidia
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
